stages:
  - build
  - test:clang-fbsd
  - test:clang
  - test:gcc
  - test:gcc-i386
  - test:clang-macOS

cache:
  paths:
  - apt-cache/

.build-meson: &build-meson
  stage: build
  script:
    - meson setup build ${BHF_CI_MESON_OPTIONS}
    - ninja -C build
    - meson setup example/build example ${BHF_CI_MESON_OPTIONS}
    - ninja -C example/build
  artifacts:
    paths:
    - build/libAdsLib.a
    - build/AdsLibTest
    - build/AdsLibTest.exe
    - build/AdsLibOOITest
    - build/AdsLibOOITest.exe
    - example/build/example
    - example/build/example.exe

.build-meson-docker: &build-meson-docker
  <<: *build-meson
  tags:
    - docker
  image: ${REGISTRY_HOST}/beckhoff/docker-mxe:25861

.build-template: &build-template
  stage: build
  tags:
    - docker
  image: ${REGISTRY_HOST}/beckhoff/docker-mxe:8187
  script:
    - $maker CXX=$compiler OS_NAME=$os_name
    - $maker CXX=$compiler OS_NAME=$os_name AdsLibTest.bin
    - $maker CXX=$compiler OS_NAME=$os_name AdsLibOOITest.bin
    - cd example
    - $maker CXX=$compiler OS_NAME=$os_name
  artifacts:
    paths:
    - AdsLib-$os_name.a
    - AdsLibTest.bin
    - AdsLibOOITest.bin
    - example/example.bin

build:clang:
  <<: *build-meson-docker
  variables:
    CXX: clang++

build:clang-fbsd:
  <<: *build-meson
  tags:
    - freebsd13_4_build_vm
  before_script:
    - doas pkg install -y meson

build:clang-macOS:
  <<: *build-meson
  tags:
    - macOS
  variables:
    BHF_CI_MESON_OPTIONS: '-Dcpp_std=c++11'

build:gcc:
  <<: *build-meson-docker

build:gcc-i386:
  <<: *build-meson-docker
  variables:
    BHF_CI_MESON_OPTIONS: '--cross-file meson.cross.amd64-linux.i386'

build:mxe:
  <<: *build-meson-docker
  variables:
    BHF_CI_MESON_OPTIONS: '--cross-file meson.cross.amd64-linux.win32 -Dcpp_std=c++11'

build:win10:
  <<: *build-meson
  tags:
    - MD_TWINCAT_XAE
  before_script:
    - C:\ProgramData\chocolatey\bin\choco install --no-progress -y meson ninja
    - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")


.test-linux: &test-linux
  image: debian:buster-slim
  tags:
    - docker
    - host_network
    - lbs1
    - rack
  before_script:
    - dpkg --add-architecture i386
    - apt-get -o dir::cache::archives="apt-cache" update
    - apt-get -o dir::cache::archives="apt-cache" install -y libc6:i386 libstdc++6:i386 ncat
  script:
    - ./tools/90_run_tests.sh

test:clang:
  <<: *test-linux
  stage: test:clang
  dependencies:
    - build:clang

test:gcc:
  <<: *test-linux
  stage: test:gcc
  dependencies:
    - build:gcc

test:gcc-i386:
  <<: *test-linux
  stage: test:gcc-i386
  dependencies:
    - build:gcc-i386

test:clang-fbsd:
  stage: test:clang-fbsd
  dependencies:
    - build:clang-fbsd
  tags:
    - fbsd
    - rack
  script:
    - ./tools/90_run_tests.sh

test:clang-macOS:
  stage: test:clang-macOS
  dependencies:
    - build:clang-macOS
  tags:
    - macOS
    - rack
  script:
    - ./tools/90_run_tests.sh
