jobs:
- job: BuildLinux
  timeoutInMinutes: 30
  pool:
    name: TcOs
    demands:
      - Agent.OS -equals Linux
      - docker
  container: patrickbr-git.beckhoff.com:5500/beckhoff/docker-mxe:8187
  steps:
  - bash: .ci/do_build.sh
    displayName: 'Building Subprojects'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: bin
      artifactName: bin
